const newHomesPortfolioItems = [
  {
    name: "The Bluff",
    href: "/portfolio/magnolia-residence/",
    image: "/wp-content/uploads/2024/04/Lawtonwood_30.jpg",
    position: "center bottom",
  },
  {
    name: "Dorothy’s House",
    href: "/portfolio/dorothys-house/",
    image: "/wp-content/uploads/2014/01/Front2_DorothyHR_1.jpg",
  },
  { name: "508 Residence", href: "/portfolio/508-residence/", image: "/wp-content/uploads/2015/12/508feature-min.jpg" },
  {
    name: "Southpaw Residence",
    href: "/portfolio/southpaw-residence/",
    image: "/wp-content/uploads/2014/02/southpawTitleHRes.jpg",
    position: "bottom left",
  },
  { name: "The Ranch", href: "/portfolio/the-ranch/", image: "/wp-content/uploads/2014/01/theRanch_ProjectsImage2000.jpg", position: "center right" },
  { name: "Pole Pass Cabin", href: "/portfolio/pole-pass-cabin/", image: "/wp-content/uploads/2015/05/LR_11054_00_Pole_Pass_N37.jpg" },
  { name: "DMG Residence", href: "/portfolio/dmg-residence/", image: "/wp-content/uploads/2016/02/CRO1558pc-e1498579808541.jpg" },
  { name: "Mercer Island Residence", href: "/portfolio/mercer-island-residence/", image: "/wp-content/uploads/2017/08/Demopulos_38_2k.jpg" },
  { name: "Arrow Bay", href: "/portfolio/arrow-bay/", image: "/wp-content/uploads/2024/10/Arrow-Bay_5692.jpg" },
  { name: "Beans-Bight Residence", href: "/portfolio/beans-bight-residence/", image: "/wp-content/uploads/2016/09/koyoDSC03424revB.jpg", position: "bottom center" },
  { name: "Union Bay Residence", href: "/portfolio/union-bay-residence/", image: "/wp-content/uploads/2017/06/Talbot_3.jpg" },
  { name: "The Perch", href: "/portfolio/comstock/", image: "/wp-content/uploads/2025/11/1_x_515_Comstock_24.jpg" },
  { name: "Madison Park", href: "/portfolio/madison-park/", image: "/wp-content/uploads/2014/01/madisonFrontPiece-390xHR2000.jpg" },
  { name: "The Cottage", href: "/portfolio/the-cottage/", image: "/wp-content/uploads/2017/09/403_Galer-304_2K.jpg", darkText: true },
  { name: "Longhouse Residence", href: "/portfolio/longhouse-residence/", image: "/wp-content/uploads/2014/02/longhouseTitleHRes.jpg" },
  { name: "Bellevue Residence", href: "/portfolio/laing-residence/", image: "/wp-content/uploads/2014/05/laing3.jpg" },
  { name: "Stone House", href: "/portfolio/stone-house/", image: "/wp-content/uploads/2014/05/stonehouse2.jpg" },
  { name: "Beans View", href: "/portfolio/beans-view/", image: "/wp-content/uploads/2025/12/2_CR_VS_Beansview-011.jpg" },
  {
    name: "Yarrow Point Residence",
    href: "/portfolio/yarrow-point-residence/",
    image: "/wp-content/uploads/2014/02/yarrowPointTitleHRes.jpg",
    position: "top center",
  },
  { name: "Phantom Lake Residence", href: "/portfolio/phantom-lake-residence/", image: "/wp-content/uploads/2014/02/phantomLakeResTitleHRes.jpg" },
  { name: "Phantom Lake Studio", href: "/portfolio/phantom-lake-studio/", image: "/wp-content/uploads/2014/05/phantomlakeStudio3.jpg" },
  { name: "Medina Residence", href: "/portfolio/obot-residence/", image: "/wp-content/uploads/2014/02/OBOTtitleHRes.jpg" },
];

export default newHomesPortfolioItems;
