const bluffImages = [
  "Lawtonwood_40.jpg",
  "Lawtonwood_11c.jpg",
  "Lawtonwood_15.jpg",
  "Lawtonwood_14c.jpg",
  "Lawtonwood_2.jpg",
  "Lawtonwood_1.jpg",
  "Lawtonwood_8and6split.jpg",
  "Lawtonwood_6.jpg",
  "Lawtonwood_20.jpg",
  "Lawtonwood_23.jpg",
  "Lawtonwood_29.jpg",
  "Lawtonwood_30.jpg",
  "Lawtonwood_31.jpg",
  "Lawtonwood_25.jpg",
  "Lawtonwood_27.jpg",
  "Lawtonwood_36.jpg",
  "Lawtonwood_18.jpg",
  "Lawtonwood_32.jpg",
  "Lawtonwood_16.jpg",
  "Lawtonwood_13_B.jpg",
  "Lawtonwood_12_B.jpg",
  "Lawtonwood_22.jpg",
  "Lawtonwood_38.jpg",
];

const dorothysHouseImages = [
  "b_DorothyHR_2.jpg",
  "c_DorothyHR_3-scaled.jpg",
  "d_DorothyHR_4-scaled.jpg",
  "e_DorothyHR_5-scaled.jpg",
  "f_DorothyHR_6-scaled.jpg",
  "g_DorothyHR_7c.jpg",
  "h_DorothyHR_8-scaled.jpg",
  "i_DorothyHR_9c.jpg",
  "j_DorothyHR_10.jpg",
  "k_DorothyHR_11.jpg",
  "l_DorothyHR_12.jpg",
  "m_DorothyHR_13.jpg",
  "n_DorothyHR_14-scaled.jpg",
  "o_DorothyHR_15.jpg",
  "p_DorothyHR_16.jpg",
];

const residence508Images = [
  "508_03.jpg",
  "508_06.jpg",
  "508_09.jpg",
  "508_10.jpg",
  "508_11.jpg",
  "508_12.jpg",
  "508_14.jpg",
  "508_31.jpg",
  "508_32.jpg",
  "508_47.jpg",
  "508_49.jpg",
  "508_58.jpg",
];

const southpawResidenceImages = [
  "southpaw26.jpg",
  "southpaw28.jpg",
  "southpaw03.jpg",
  "southpaw18.jpg",
  "southpaw20.jpg",
  "southpaw11.jpg",
  "southpaw17.jpg",
  "southpaw04.jpg",
  "southpaw06.jpg",
  "southpaw07.jpg",
  "southpaw08.jpg",
  "southpaw10.jpg",
  "southpaw16.jpg",
  "southpaw15.jpg",
  "southpaw23.jpg",
  "southpaw24.jpg",
];

const mercerIslandResidenceImages = [
  "Demopulos_43_2k.jpg",
  "Demopulos_14_2k.jpg",
  "Demopulos_1_2kB.jpg",
  "Demopulos_16_2kB.jpg",
  "Demopulos_28_2k.jpg",
  "Demopulos_31_2k.jpg",
  "Demopulos_15_2k.jpg",
  "Demopulos_33_2k.jpg",
  "Demopulos_34_2k.jpg",
  "Demopulos_27_2k.jpg",
  "Demopulos_12_2k.jpg",
  "Demopulos_13_2k.jpg",
  "Demopulos_19_2kB.jpg",
  "Demopulos_2k.jpg",
  "Demopulos_24_2k.jpg",
  "Demopulos_21_2k.jpg",
  "Demopulos_22_2k.jpg",
  "Demopulos_4_2k.jpg",
  "Demopulos_17_2k.jpg",
  "Demopulos_25_2k.jpg",
  "Demopulos_6_2k.jpg",
  "Demopulos_36_2k.jpg",
  "Demopulos_35_2k.jpg",
const polePassCabinImages = [
  "LR_11054_00_Pole_Pass_N21.jpg",
  "LR_11054_00_Pole_Pass_N19.jpg",
  "LR_11054_00_Pole_Pass_N18.jpg",
  "LR_11054_00_Pole_Pass_N17.jpg",
  "LR_11054_00_Pole_Pass_N14.jpg",
  "LR_11054_00_Pole_Pass_N13.jpg",
  "LR_11054_00_Pole_Pass_N10.jpg",
  "LR_11054_00_Pole_Pass_N9.jpg",
  "LR_11054_00_Pole_Pass_N8.jpg",
  "Pole_Pass_waterView2Kwide72ppiLR.jpg",
  "LR_11054_00_Pole_Pass_N37.jpg",
const theRanchImages = [
  "theRanch02.jpg",
  "theRanch03.jpg",
  "theRanch04.jpg",
  "theRanch05.jpg",
  "theRanch06.jpg",
  "theRanch07.jpg",
  "theRanch08.jpg",
  "theRanch09.jpg",
  "theRanch10.jpg",
  "theRanch11.jpg",
  "theRanch12.jpg",
  "theRanch13.jpg",
  "theRanch14.jpg",
  "theRanch15.jpg",
  "theRanch16.jpg",
  "theRanch17.jpg",
  "theRanch18.jpg",
  "theRanch19.jpg",
  "theRanch20.jpg",
  "theRanch21.jpg",
  "theRanch22.jpg",
];

const portfolioProjectPages = {
  "the-bluff": {
    slug: "the-bluff",
    title: "The Bluff",
    category: "New Homes",
    location: "Seattle, Washington",
    heroImage: "/wp-content/uploads/2024/04/Lawtonwood_41Balt.jpg",
    previousHref: "/portfolio/new_homes/",
    nextHref: "/portfolio/dorothys-house/",
    description: [
      "An in-city retreat, situated on a low bluff over-looking the Salish Sea, the design team responded to the clients desire for this home to meld with the surrounding landscape. Muscular in its construction with substantial concrete and steel elements the home burrows into the hillside, with more than half the structure below ground, greatly reducing its scale.",
      "Interiors celebrate board form concrete, unadorned structural steel and reclaimed finishes including surfaces clad in beetle-kill pine. The great room two story volume focuses the view to the west, across the bay to the Olympic mountain range beyond.",
      "A solar array, ground source heat and cooling system, planted roofs and significant portions of the building built in-ground help lower energy consumption.",
    ],
    details: [
      {
        label: "Architect:",
        lines: ["Deforest Architects: John Deforest, Melissa Nordquist, Geoff Briggs"],
        links: [{ label: "www.deforestarchitects.com", href: "https://www.deforestarchitects.com" }],
      },
      {
        label: "Interiors:",
        lines: ["Lucas Design", "NB Design"],
        links: [
          { label: "www.lucasinterior.com", href: "https://www.lucasinterior.com" },
          { label: "www.nbdesigngroup.net", href: "https://www.nbdesigngroup.net" },
        ],
      },
      {
        label: "Landscape Architect:",
        lines: ["Atelier PS Landscape Architecture Urbanism, Charles Anderson"],
        links: [{ label: "www.charlesanderson.com", href: "https://www.charlesanderson.com" }],
      },
      {
        label: "Photography:",
        lines: ["Benjamin Benschneider Photography"],
        links: [{ label: "www.benschneiderphoto.com", href: "https://www.benschneiderphoto.com" }],
      },
    ],
    galleryImages: bluffImages.map((image) => ({
      src: `/wp-content/uploads/2024/04/${image}`,
      alt: `The Bluff - ${image.replace(/\.jpg$/i, "")}`,
    })),
  },
  "dorothys-house": {
    slug: "dorothys-house",
    title: "Dorothy's House",
    category: "New Homes",
    location: "Seattle, Washington",
    heroImage: "/wp-content/uploads/2024/09/a_DorothyHR_1.jpg",
    previousHref: "/portfolio/the-bluff/",
    nextHref: "/portfolio/508-residence/",
    description: [
      "A tree house at waters edge, this home is located in a forested setting, with a number of natural constraints including an adjacent stream running through the property. The narrow footprint inspired a bold cantilever supported by two steel trusses reaching toward the waters edge. Challenging site access required significant off-site fabrication with a bolt-together construction that was embraced by the buildings architecture.",
      "The dramatic retreat has a reserved palette, incorporating cost effective finishes including aluminum clad windows and doors, drywall and applied trim. Reclaimed lighting fixtures from the previous home, stainless woven fabric acting as a guard rail, driftwood colored wire brushed casework accents and patinated steel emphasize its proximity to the salt water environment.",
    ],
    details: [
      {
        label: "Architect:",
        lines: ["Deforest Architects: John Deforest, Rosie Donavan"],
        links: [{ label: "www.deforestarchitects.com", href: "https://www.deforestarchitects.com" }],
      },
      {
        label: "Interiors:",
        lines: ["Lucas Design: David and Suzie Lucas"],
        links: [{ label: "www.lucasinterior.com", href: "https://www.lucasinterior.com" }],
      },
      {
        label: "Landscape Architect:",
        lines: ["SCJ Studio Landscape Architecture: Mark Garff"],
        links: [{ label: "www.scjstudiola.com", href: "https://www.scjstudiola.com" }],
      },
      {
        label: "Photography:",
        lines: ["Benjamin Benschneider Photography"],
        links: [{ label: "www.benschneiderphoto.com", href: "https://www.benschneiderphoto.com" }],
      },
    ],
    galleryImages: dorothysHouseImages.map((image) => ({
      src: `/wp-content/uploads/2024/09/${image}`,
      alt: `Dorothy's House - ${image.replace(/\.jpg$/i, "")}`,
    })),
  },
  "508-residence": {
    slug: "508-residence",
    title: "508 Residence",
    category: "New Homes",
    location: "Washington Park, Seattle, Washington",
    heroImage: "/wp-content/uploads/2014/02/508_01.jpg",
    previousHref: "/portfolio/dorothys-house/",
    nextHref: "/portfolio/southpaw-residence/",
    description: [
      "A modern masterpiece, the design team worked with a palette of four primary materials: concrete, wood, steel and stone. The surfaces of these materials received finishes in rich warm tones and texture, all installed with extreme precision. High ceilings and a wall of windows running parallel with the lake allow natural light to fill the airy open rooms.",
      "Sandstone-paved terraces link the house to the landscape at both the street side and lake side. Maples and black pines nearly 100 years old serve as living pieces of sculpture along side modern steel sculpture and antique Chinese stone benches. Energy-conscious features include a ground-source heat pump and green roofs.",
    ],
    details: [
      {
        label: "Architect:",
        lines: [
          "Peter Conard principal architect",
          "Freya Johnson project architect",
          "Conard Romano Architects (formerly Sullivan Conard Architects)",
        ],
        links: [{ label: "www.conardromano.com", href: "https://www.conardromano.com" }],
      },
      {
        label: "Interiors:",
        lines: ["Doug Rasar Interior Design", "ds@rasarinteriors.com"],
      },
      {
        label: "Landscape Architect:",
        lines: ["Allworth Design"],
        links: [{ label: "www.allworthdesign.com", href: "https://www.allworthdesign.com" }],
      },
      {
        label: "Photography:",
        lines: ["Aaron Leitz Photography"],
        links: [{ label: "www.aaronleitz.com", href: "https://www.aaronleitz.com" }],
      },
    ],
    galleryImages: residence508Images.map((image) => ({
      src: `/wp-content/uploads/2014/02/${image}`,
      alt: `508 Residence - ${image.replace(/\.jpg$/i, "")}`,
    })),
  },
  "southpaw-residence": {
    slug: "southpaw-residence",
    title: "Southpaw Residence",
    category: "New Homes",
    location: "Seward Park, Seattle, Washington",
    heroImage: "/wp-content/uploads/2014/02/southpaw21.jpg",
    previousHref: "/portfolio/508-residence/",
    nextHref: "/portfolio/teanaway-ranch/",
    description: [
      "Unconventional, inventive and daring. Rather than conforming to the typical front yard, house, back yard site plan, the architects boldly chose to locate the house its long axis running East to West, and shifted toward the North property line, in order to create a sunny south facing modern villa with a courtyard that serves as an outdoor living space.",
      "Equally bold is the use of air-placed concrete structural walls, finished with true integral color trowel finished cement stucco, resulting in walls that appear to be carved from a single block of stone. The north wall of the home is monolithic exposed smooth concrete, over 75′ long, 28′ tall and 2′ thick.",
      "Metal roofing, and steel windows and doors create a building shell that will age gracefully with virtually no maintenance. The interiors feature exposed steel and reclaimed fir beams and ceilings, Moroccan tile mosaic floors and a sinuous, sculptural steel stair railing.",
    ],
    details: [
      {
        label: "Architect:",
        lines: ["Replinger Hossner Osolin Architects"],
        links: [{ label: "www.rhoarchitects.com", href: "https://www.rhoarchitects.com" }],
      },
      {
        label: "Interiors:",
        lines: ["Janice Viekman"],
        links: [{ label: "www.viekman.com", href: "https://www.viekman.com" }],
      },
      {
        label: "Landscape Architect:",
        lines: ["Allworth Nussbaum"],
        links: [{ label: "www.allworthnussbaum.com", href: "https://www.allworthnussbaum.com" }],
      },
      {
        label: "Photography:",
        lines: ["Lara Swimmer Photography"],
        links: [{ label: "www.swimmerphoto.com", href: "https://www.swimmerphoto.com" }],
      },
    ],
    galleryImages: southpawResidenceImages.map((image) => ({
      src: `/wp-content/uploads/2014/02/${image}`,
      alt: `Southpaw Residence - ${image.replace(/\.jpg$/i, "")}`,
    })),
  },
  "mercer-island-residence": {
    slug: "mercer-island-residence",
    title: "Mercer Island Residence",
    category: "New Homes",
    location: "Mercer Island, Washington",
    heroImage: "/wp-content/uploads/2017/08/Demopulos_40_2K.jpg",
    previousHref: "/portfolio/dmg-residence/",
    nextHref: "/portfolio/arrow-bay/",
    description: [
      "This lakefront home, sited in a descending wooded property, displays an uncommon level of craft. Intricate detail and intersections of unusual materials pushed the project's artisans and craftspeople to bring out their best.",
      "Lake and woodland views are captured and deliberately framed on all levels of the building. Expansive walls of glass flood the home with light. Artfully designed steel fins at the exterior adorn the house while shielding from summer sun.",
      "Cerused casework and doors, custom metalwork with plated finish, venetian plaster, leather paneling and complex wood joinery throughout lend a richness and warmth to the interiors.",
  "pole-pass-cabin": {
    slug: "pole-pass-cabin",
    title: "Pole Pass Cabin",
    category: "New Homes",
    location: "Orcas Island, Washington",
    heroImage: "/wp-content/uploads/2015/05/LR_11054_00_Pole_Pass_N7.jpg",
    previousHref: "/portfolio/teanaway-ranch/",
    nextHref: "/portfolio/dmg-residence/",
    description: [
      "A secluded family retreat located in the San Juan islands of Washington State. This is the modern expression of a cabin — built with an engineered steel frame and walls of glass.",
      "On two faces of the building, entire walls slide open, driven by a hand-cranked gear that opens the home to the outdoors. Second-growth clear Douglas fir framing creates warm and rich ceilings. Fir plywood and blackened steel wrap interior walls, punctuated by functional walls of tile or a custom steel vanity painted Lockhart|Suver orange.",
      "Planted roofs elevate two rectangular planes of grass field to serve as natural terraces for the upper-floor master suite. The exterior is clad with traditional Japanese shou sugi ban charred cedar plank siding.",
  "the-ranch": {
    slug: "the-ranch",
    title: "The Ranch",
    category: "New Homes",
    location: "Eastern Washington",
    heroImage: "/wp-content/uploads/2023/02/theRanch01.jpg",
    previousHref: "/portfolio/southpaw-residence/",
    nextHref: "/portfolio/pole-pass-cabin/",
    description: [
      "Home, home on the range… Nestled into the lee of a hill, while taking advantage of expansive views of the surrounding prairie and wooded hillside beyond, the clients envisioned a contemporary take on the classic ranch home. Board form concrete, corrugated exterior wall paneling, re-sawn fir timber bolt frame and steel windows and doors give an integrity to the design while also acting as a bulwark against the sometimes harsh environment of the Cascade range.",
      "Tucking a portion of the home and garage into the natural slope, choosing a darker color palette for the exterior, building a separate bunk house for family and guests—these elements combined, serve to harmonize and ease the overall visual scale of the residence into the beautiful, rolling Eastern Washington landscape. Substantial overhangs provide shade in the hot summers and a buffer from snowy winters. Generous gathering spaces on the interior, matched with the clients fearless embrace of color and texture, foster a fun and inviting feel.",
    ],
    details: [
      {
        label: "Architect:",
        lines: ["Brett Baba and Noreen Shinohara", "Graham Baba Architects"],
        links: [{ label: "www.grahambabaarchitects.com", href: "https://www.grahambabaarchitects.com" }],
      },
      {
        label: "Interiors:",
        lines: ["Terry Hunziker Design"],
        links: [{ label: "www.terryhunziker.com", href: "https://www.terryhunziker.com" }],
      },
      {
        label: "Landscape Architect:",
        lines: ["Rich Haag and Anne James", "Rich Haag & Assoc."],
        links: [{ label: "www.richhaagassoc.com", href: "https://www.richhaagassoc.com" }],
      },
      {
        label: "Photography:",
        lines: ["Kevin Scott"],
        links: [{ label: "www.kevinscott.us", href: "https://www.kevinscott.us" }],
      },
    ],
    galleryImages: mercerIslandResidenceImages.map((image) => ({
      src: `/wp-content/uploads/2017/08/${image}`,
      alt: `Mercer Island Residence - ${image.replace(/\.jpg$/i, "")}`,
        lines: [
          "Tom Kundig principal architect",
          "Mark Olthoff and Chris Gerrick project architects",
          "Olson Kundig Architects",
        ],
        links: [{ label: "www.olsonkundig.com", href: "https://www.olsonkundig.com" }],
      },
      {
        label: "Interiors:",
        lines: ["Debbie Kennedy", "Olson Kundig Architects"],
      },
      {
        label: "Photography:",
        lines: ["Benjamin Benschneider Photography"],
        links: [{ label: "www.benschneiderphoto.com", href: "https://www.benschneiderphoto.com" }],
      },
    ],
    galleryImages: polePassCabinImages.map((image) => ({
      src: image === "Pole_Pass_waterView2Kwide72ppiLR.jpg" ? `/wp-content/uploads/2015/07/${image}` : `/wp-content/uploads/2015/05/${image}`,
      alt: `Pole Pass Cabin - ${image.replace(/\.jpg$/i, "")}`,
        lines: ["Tim Hossner, Jim Replinger, Christopher Osolin, and Stacie Conway", "rho Architects"],
        links: [{ label: "www.rhoarchitects.com", href: "https://www.rhoarchitects.com" }],
      },
      {
        label: "Interiors:",
        lines: ["Maryika Byskiniewicz", "SPACES"],
        links: [{ label: "www.maryika-spaces.com", href: "https://www.maryika-spaces.com" }],
      },
      {
        label: "Landscape Architect:",
        lines: ["Bruce Hinckley and Mario Laky", "Alchemie"],
        links: [{ label: "alchemiesites.com", href: "https://alchemiesites.com" }],
      },
      {
        label: "Photography:",
        lines: ["Andrew Pogue", "Pogue"],
        links: [{ label: "www.andrewpogue.com", href: "https://www.andrewpogue.com" }],
      },
    ],
    galleryImages: theRanchImages.map((image) => ({
      src: `/wp-content/uploads/2023/02/${image}`,
      alt: `The Ranch - ${image.replace(/\.jpg$/i, "")}`,
    })),
  },
};

export default portfolioProjectPages;
